host: "dml1-scan"
port: "1521"
username: "saturn"
password: "saturn"
url: "http://11.120.101.176:8180/saturn"
tenant: "MCOM"
sid: "srvprf01"
regression: true
stellahost: dml1-scan
stellasid: "dpmprf01"
stellausername: "macys"
stellapassword: "macys"
astrahost: "11.120.36.12"
astrasid: "dpmstg01"
astrausername: "cmsusr"
astrapassword: "cmsusr"  
attrservicehost : dml1-scan
attrservicesid : dpmqas01
attrserviceusername : stars_attr
attrservicepwd : stars_attr
sitetenant : MCOM  
url1: "http://11.120.101.176:8080/saturn/login"    
stellaui: "http://11.120.98.88:8080/UI/Common/Html/Login.jsp"