host: "dmj1-scan"
port: "1521"
username: "saturn"
password: "saturn"
url: "http://11.120.101.177:8080/saturn"
tenant: "BCOM"
sid: "dpmsrv01"
regression: true
stellahost: dml1-scan
stellasid: "dpmqa01"
stellausername: "macys"
stellapassword: "macys"
astrahost: "11.120.115.39"
astrasid: "dpmqa01"
astrausername: "cmsusr"
astrapassword: "cmsusr" 
attrservicehost : dmj1-scan
attrservicesid : dpmsrv01
attrserviceusername : stars_attr
attrservicepwd : stars_attr