host: "11.120.101.204"
port: "1521"
sid: "stelladev"
username: "saturn"
password: "saturn"
url: "http://11.120.101.115:8080/saturn"
tenant: "BCOM"
regression: false
stellahost: 11.120.100.34
stellasid: bsd9
stellausername: "macys"
stellapassword: "macys"
astrahost: "11.120.100.34"
astrasid: "bsd6"
astrausername: "bcmsusr"
astrapassword: "bcmsusr"   