host: "mdc2vr5211"
port: "1521"
sid: "ci213"
username: "saturn"
password: "saturn"
url: "http://11.120.101.30:8180/saturn/"
tenant: "MCOM"
regression: false
stellahost: mdc2vr5211
stellasid: ci213
stellausername: "macys"
stellapassword: "macys"
astrahost: "11.120.100.34"
astrasid: "bsd6"
astrausername: "cmsusr"
astrapassword: "cmsusr"   
attrservicehost : 11.120.101.71
attrservicesid : int12
attrserviceusername : stars_attr
attrservicepwd : stars_attr
sitetenant: MCOM 
url1: "http://11.120.101.76:8180/saturn/"
stellaui: "http://11.120.101.30:8080/UI/Common/Html/Login.jsp"
